src/BookShop.Web/Components/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookShop.Web.Components
{
    public class LoginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/BookShop.Web/Components/MenuViewComponent.cs
using BookShop.Web.Infrastructure;
using BookShop.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.ClientRepository;
using Repository.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookShop.Web.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private CatRepository catRepo;
        public MenuViewComponent(CatRepository catRepo)
        {
            this.catRepo = catRepo;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.cartNumber = GetCart().Lines.Count();
            IEnumerable<Cat> cat = await catRepo.GetCatSub();
            return View(cat);
        }
        private Cart GetCart()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
            return cart;
        }
    }
}

src/BookShop.Web/Components/SignupViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookShop.Web.Components
{
    public class SignupViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/BookShop.Web/Views/Shared/Footer.cshtml
<footer class="c-layout-footer c-layout-footer-4 c-bg-footer-8">
    <div class="c-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 c-footer-4-p-right">
                    <div class="c-content-title-1">
                        <h3 class="c-font-uppercase c-font-bold c-font-white c-border">
                            BOOK
                            <span class="c-theme-font">SHOP</span>
                        </h3>
                    </div>
                    <p class="c-about"> Trang bán sách trực tuyến với những đầu sách đa dạng, giá cả cạnh tranh cùng dịch vụ ưu đãi cho khách hàng.</p>
                    <div class="c-links">
                        <ul class="c-nav">
                            <li>
                                <a class="c-active c-theme-border c-theme-font" href="/">Trang chủ</a>
                            </li>
                            <li>
                                <a asp-action="List" asp-controller="Home" asp-route-page="1">Loại sách</a>
                            </li>
                        </ul>
                    </div>
                    <p class="c-contact">
                        101/70 Bùi Minh Trực, P5, Q8
                        <br> Phone: 0943 252 265
                        <br> Fax: 0943 252 265
                    </p>
                    <ul class="c-socials">
                        <li>
                            <a href="#">
                                <i class="icon-social-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-social-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-social-youtube"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-social-dribbble"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6 c-footer-4-p-left">
                    <div class="c-feedback">
                        <h3 class="c-font-thin">Liên hệ với chúng tôi</h3>
                        <form action="#">
                            <input type="text" placeholder="Tên" class="form-control">
                            <input type="text" placeholder="Email" class="form-control">
                            <textarea rows="8" name="message" placeholder="Nội dung ..." class="form-control"></textarea>
                            <button type="submit" class="btn c-btn-white c-btn-border-2x c-btn-uppercase btn-lg c-btn-bold c-btn-square">Gửi</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

src/BookShop.Web/Views/Shared/Header.cshtml
@model string

<div class="c-content-box c-size-md c-bg-parallax" style="background-image: url(/img/content/backgrounds/bg-54.jpg)">
    <div class="container" style="min-height:120px">
        <div class="c-page-title c-center" style="margin-top:70px;">
            <h1 class="c-font-uppercase c-font-sbold" style="color:white;">@Model</h1>
        </div>
    </div>
</div>

src/BookShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - BookShop</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700&amp;subset=all' rel='stylesheet' type='text/css'>
    <link href="~/css/global.min.css" rel="stylesheet" asp-append-version="true" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN: BASE PLUGINS  -->
    <link href="~/css/base.min.css" rel="stylesheet" asp-append-version="true" />
    <!-- END: BASE PLUGINS -->
    <!-- BEGIN THEME STYLES -->
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="/favicon.ico" />
</head>
<body class="c-layout-header-fixed c-layout-header-mobile-fixed c-layout-header-fullscreen">
    <!-- BEGIN: HEADER -->
    @await Component.InvokeAsync("Menu")
    <!-- END: HEADER -->


    @await Component.InvokeAsync("Signup")


    @await Component.InvokeAsync("Login")

    <!-- BEGIN: PAGE CONTAINER -->
    <div class="c-layout-page">
        @RenderBody()
    </div>

    <div id="relatedProModal" class="modal fade bs-example-modal-lg custom-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="false">
        <div class="modal-dialog modal-lg modal-lg-custom">
            <div class="modal-content c-square">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myLargeModalLabel">Sản phẩm liên quan</h4>
                </div>
                <div id="relModalBody" class="modal-body">
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- END: PAGE CONTAINER -->
    <!-- BEGIN: LAYOUT/FOOTERS/FOOTER-2 -->
    <a name="footer"></a>
    @Html.Partial("Footer")
    <!-- END: LAYOUT/FOOTERS/FOOTER-2 -->

    <div class="c-layout-go2top">
        <i class="icon-arrow-up"></i>
    </div>


    <!-- BEGIN: CORE PLUGINS -->
    <script src="~/js/core.min.js" type="text/javascript"></script>
    <!-- END: CORE PLUGINS -->
    <!-- BEGIN: LAYOUT PLUGINS -->
    <script src="~/js/layout.min.js" type="text/javascript"></script>
    <!-- END: LAYOUT PLUGINS -->
    <!-- BEGIN: THEME SCRIPTS -->
    <script src="~/js/site.min.js" type="text/javascript"></script>
    <script>
            $(document).ready(function()
            {
                App.init(); // init core
            });
    </script>
    <!-- END: THEME SCRIPTS -->
    <!-- BEGIN: PAGE SCRIPTS -->
    @RenderSection("scripts", required: false)
    <script src="/js/bootstrap-notify.min.js" type="text/javascript"></script>
    @if (TempData["Message"] != null)
    {
        <script>
        $.notify({
            // options
            message: '@((TempData["Message"] as string[])[1])'
        }, {
            // settings
            type: '@((TempData["Message"] as string[])[0])',
            placement: {
                from: "bottom",
                align: "center"
            },
            animate: {
                enter: 'animated fadeInUp',
                exit: 'animated fadeOutDown'
            },
            delay: 2000,
            mouse_over : "pause"
        });
        </script>
    }
    <script src="~/js/site.js" type="text/javascript"></script>
    <!-- END: PAGE SCRIPTS -->
</body>
</html>